### ISSUE TITLE
Valencia 3-velocity notation in the documentation

### ISSUE THREAD

**Issue by AnujKankani** [GRHayL/GRHayL#64]
In the "Derivation of the GRMHD Evolution Equations" section of the wiki, specifically in the "Evolution Equations for the Conservative Variables" subsection, the third equation defines the Valencia 3-velocity, I believe the LHS should be \tilde{v}^i and not \tilde{u}^i as it is now. The LHS is the 3-velocity, not the 4-velocity. Similarly right below where the lorentz factor W is defined, the same switch should be made, unless I am misunderstanding something. This would be consistent with the definition in the GRHydro paper eq. (14) and eq. (10) of the IllinoisGRMHD paper.

**Comment by SamuelCupp** [comment]
Sorry for the slow response time. I was traveling, then I was sick. The u tilde notation is just one we made up, but I see why it could be more reasonable to change it to v tilde. If I recall correctly, both are referred to as just "v" in their respective papers, so I had to change the GRHydro variable to something else. I'll try to go through and change this by the end of the week.
